FROM cohorte/runtime:1.3.2-java-win1809

#-----------------------------------------------------------------------------
# Cohorte Runtime image.
#
# Cohorte Platform version: 1.2.1
#-----------------------------------------------------------------------------

MAINTAINER "Aurélien Pisu" <aurelien.pisu@cohorte-technologies.com>

ENV REFRESHED_AT 20170707_1130

# Installation commands

ENV COHORTE_BASE /opt/node
ENV COHORTE_DATA /opt/node/data

RUN mkdir ./opt/node/
RUN mkdir ./opt/node/data

COPY ./install/run.sh ./opt


RUN sh -c "chmod +x ./opt/run.sh"


ENTRYPOINT ["bash","./opt/run.sh"]


VOLUME [ "/opt/node" ]

EXPOSE 9000 9001 8000 8001 8002 8003 8004 8005 8006 8007 8008 8009 8010
