FROM cohorte/base:1.5-win1809

#-----------------------------------------------------------------------------
# Cohorte Runtime image.
#
# Cohorte Platform version: 1.2.1
#-----------------------------------------------------------------------------

MAINTAINER "Bassem Debbabi" <bassem.debbabi@cohorte-technologies.com>

ENV REFRESHED_AT 20170707_1130

ENV COHORTE_HOME /opt/cohorte 

COPY ./install/cohorte.tar.gz ./opt/cohorte.tar.gz

RUN sh -c "cd ./opt ; tar xvf cohorte.tar.gz"
RUN sh -c "rm -f ./opt/cohorte.tar.gz"
RUN sh -c "ls -l ./opt"
RUN sh -c "mv -f ./opt/cohorte-* ./opt/cohorte"
RUN sh -c "ls -l ./opt"
RUN sh -c "cd ${COHORTE_HOME}"
