FROM cohorte/base:1.5-win1909

#-----------------------------------------------------------------------------
# Cohorte Runtime image.
#
# Cohorte Platform version: 1.2.1
#-----------------------------------------------------------------------------

MAINTAINER "Bassem Debbabi" <bassem.debbabi@cohorte-technologies.com>

ENV REFRESHED_AT 20170707_1130

ENV COHORTE_HOME /opt/cohorte 

COPY ./install/cohorte.tar.gz ./opt/cohorte.tar.gz

RUN C:/Program\ File/Git/bin/bash.exe -c "cd ./opt ; tar xvf cohorte.tar.gz"
RUN C:/Program\ File/Git/bin/bash.exe -c "rm -f ./opt/cohorte.tar.gz"
RUN C:/Program\ File/Git/bin/bash.exe -c "ls -l ./opt"
RUN C:/Program\ File/Git/bin/bash.exe -c "mv -f ./opt/cohorte-* ./opt/cohorte"
RUN C:/Program\ File/Git/bin/bash.exe -c "ls -l ./opt"
