#!/bin/bash

# User-specific bootstrapping configuration
if test -z "$COHORTE_HOME"
	then
		echo
		echo "[ERROR] the system environment's variable COHORTE_HOME is not defined!"	
		echo
		exit
fi

# Updating PYTHONPATH 
base=$(pwd)
export PYTHONPATH=${PYTHONPATH:="$base/lib:$base/repo"}

# Set node name
if test $# -gt 0; then
	if [[ $1 == -* ]]; then
		export COHORTE_NODE_NAME=${PWD##*/}
	else
		export COHORTE_NODE_NAME=$1
		shift
	fi
else
	export COHORTE_NODE_NAME=${PWD##*/}
fi

# Run COHORTE
echo
echo "[INFO] starting COHORTE ..."
sh $COHORTE_HOME/bin/cohorte-start-node $(pwd) $*
