#!/bin/bash

# User-specific bootstrapping configuration
if test -z "$COHORTE_HOME"
	then
		echo
		echo "[ERROR] the system environment's variable COHORTE_HOME is not defined!"	
		echo
		exit
fi

# Updating PYTHONPATH 
base=$(pwd)

node_name=${PWD##*/}
http="-1"
shell="0"

function is_numeric {
	re='^[0-9]+$'
	if ! [[ $1 =~ $re ]] ; then
	   return 1
	fi
	return 0
}
function is_option {
	if ! [[ $1 == -* ]] ; then	
		return 1
	fi
	return 0
}

# parameters
while test ${#} -gt 0
do
  if is_option $1 ; then	  	
	break
  elif is_numeric $1 ; then
  	if test "$http" == "-1"; then
  		http="$1"
  	else
  		shell="$1"
  	fi
  else
  	node_name="$1"
  fi
  shift
done

if test "$http" == "-1"; then
	http="0"
fi

echo 
echo "[INFO] starting node '$node_name' on http port '$http' with shell port '$shell'..."  
echo 

sh $COHORTE_HOME/bin/cohorte-start-node $base $node_name $http $shell $*
