FROM cohorte/runtime:1.3.2-java-ubuntu

#-----------------------------------------------------------------------------
# Cohorte Runtime image.
#
# Cohorte Platform version: 1.2.1
#-----------------------------------------------------------------------------

MAINTAINER "Bassem Debbabi" <bassem.debbabi@cohorte-technologies.com>

ENV REFRESHED_AT 20170707_1130

# Installation commands

ENV COHORTE_BASE /opt/node
ENV COHORTE_DATA /opt/data

RUN mkdir -p $COHORTE_BASE
RUN mkdir -p $COHORTE_DATA
# not possible to have pip 3.4 ith ubuntu 18.04

COPY ./install/init_* /opt/
COPY ./install/run.sh /opt/

RUN chmod +x /opt/init*.sh
RUN chmod +x /opt/run.sh

RUN ls -l /opt

ENTRYPOINT ["/opt/run.sh"]

EXPOSE 9000 9001 8000 8001 8002 8003 8004 8005 8006 8007 8008 8009 8010
